frontend/src/components/Cards.tsx
frontend/src/types/index.ts

Added a card type and made the card and cards component look a little better.

✨ feat: card typing and proper card component

---

frontend/package-lock.json
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/App.tsx
frontend/src/components/Cards.tsx
frontend/src/components/PercentageBarChart.tsx
frontend/src/components/ui/chart.tsx
frontend/src/pages/Collection.tsx
frontend/src/pages/Overview.tsx

Imports and Type Definitions
Imported the PercentageBarChart component.
Imported necessary types from appwrite and react.
Defined the GradientCardProps interface for the [GradientCard] component.
Chart Data and Configuration
Defined chartData and chartConfig constants to be used by the PercentageBarChart component.
GradientCard Component
Created a [GradientCard] functional component that displays a title, paragraph, and gradient background.
Overview Component
Created the Overview functional component that accepts [user] and [ownedCards] as props.
Calculated the total number of owned cards.
Rendered the main content if the user is logged in, including:
A summary of the number of card types and total cards owned.
Gradient cards with descriptive text.
Percentage bar charts to visualize card …

Overview page v1

---

frontend/src/components/Cards.tsx

Id and name are now under the card image in collection.
Made sure if the name was too long it didn't break the styling.
Just wanted to make a quick commit to contribute something, let me know if it works and I'll try to think on working for something more useful in the project.

Added card info under the image in collection

---

frontend/package-lock.json
frontend/src/components/ui/Header.tsx
frontend/src/pages/trade/BuyingTokens.tsx
frontend/src/pages/trade/ForTrade.tsx
frontend/src/pages/trade/LookingFor.tsx
frontend/src/pages/trade/Trade.tsx
frontend/src/pages/trade/components/GoTrackYourCards.tsx
frontend/src/pages/trade/components/NoCardsNeeded.tsx
frontend/src/pages/trade/components/NoSellableCards.tsx
frontend/src/pages/trade/components/NoTradeableCards.tsx
frontend/src/pages/trade/components/UserNotLoggedIn.tsx
package-lock.json

#108 
- Removed the option for people to click on Trade if they are not logged in
- If they somehow get to the page, then they will see a message to go log in
- If the user is logged in, but doesn't have any needed cards, tradeable cards, or sellable cards, then they get a proper response

Update Proper Values for Trade Pages

---

frontend/src/components/FancyCard.tsx
frontend/src/components/ui/card-table.tsx
frontend/src/lib/CardsDB.ts
frontend/src/pages/collection/CardDetail.tsx
frontend/src/pages/collection/Collection.tsx
frontend/src/pages/collection/components/Pack.tsx
frontend/src/pages/trade/BuyingTokens.tsx
frontend/src/pages/trade/Trade.tsx
frontend/src/pages/trade/components/BuyingTokensCard.tsx
frontend/src/pages/trade/components/ForTradeCard.tsx
frontend/src/pages/trade/components/LookingForCard.tsx

- Fixed Trade Buying Tokens Calculation  #129 
- Updated Trade Style To Match Rest Of Application #129 
- Fixed Order of Collection All Packs #135 
- Updated Card Images To Pull From Local Images #41

Many Fixes

---

.idea/workspace.xml
frontend/src/pages/overview/Overview.tsx

Remember the rarity filter state when used with localstorage #177

Remember the rarity filter state when used #177

---

.gitignore
frontend/src/components/BatchUpdateDialog.tsx

Added a state variable to disable bulk upload button until the user adjusts the amount variable
Resolves #230

Added a state variable to disable bulk upload button until the user adjusts

---

frontend/public/locales/en/header.json
frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/pages/export/Export.tsx
frontend/src/pages/export/components/ExportWriter.tsx
frontend/src/pages/import/Import.tsx
frontend/src/pages/import/components/ImportReader.tsx
frontend/src/types/index.ts

Export saves a file in CSV format with all your cards and the amount.  Import takes in the CSV file from export and then overwrites all the card values.  The options are in the Account Dropdown area.
This DEFINATELY needs some style polishing, but the core logic of the updating cards and outputting cards works great
#121

Import Export Feature

---

themed-collections/genetic-apex/normal/a-big-snorlax-nuisance.json
themed-collections/genetic-apex/normal/a-day-with-family.json
themed-collections/genetic-apex/normal/category-mouse-pokemon.json
themed-collections/genetic-apex/normal/collect-3-electrode-cards.json
themed-collections/genetic-apex/normal/collect-5-charizard-cards.json
themed-collections/genetic-apex/normal/collect-5-gardevoir-cards.json
themed-collections/genetic-apex/normal/collect-5-mewtwo-cards.json
themed-collections/genetic-apex/normal/different-journeys-different-growth.json
themed-collections/genetic-apex/normal/electabuzz-and-magmar.json
themed-collections/genetic-apex/normal/first-choice.json
themed-collections/genetic-apex/normal/pidgey-squad.json
themed-collections/genetic-apex/normal/pokemon-of-ancient-times.json
themed-collections/genetic-apex/normal/pokemon-super-express.json
themed-collections/genetic-apex/normal/safari-zone.json
themed-collections/genetic-apex/normal/the-gym-leaders-of-the-kanto-region.json
themed-collections/genetic-apex/normal/the-legendary-flight.json
themed-collections/genetic-apex/normal/touring-the-kanto-region.json
themed-collections/genetic-apex/normal/triple-power.json
themed-collections/genetic-apex/normal/viridian-forest.json
themed-collections/genetic-apex/secret/complete-the-kanto-pokedex.json
themed-collections/genetic-apex/secret/genetic-apex-museum-1-mewtwo.json
themed-collections/genetic-apex/secret/genetic-apex-museum-2-charizard.json
themed-collections/genetic-apex/secret/genetic-apex-museum-3-pikachu.json
themed-collections/genetic-apex/secret/the-gym-leaders-of-the-kanto-region-2.json
themed-collections/genetic-apex/secret/the-immersive-4.json
themed-collections/genetic-apex/secret/the-legendary-flight-continues.json

Creates a .json file for each themed collection mission (normal and secret) in the Genetic Apex expansion

Add Genetic Apex themed collection JSONs

---

frontend/public/locales/fr/complete-progress.json
frontend/public/locales/fr/edit-profile.json
frontend/public/locales/fr/expansion-overview.json
frontend/public/locales/fr/gradient-card.json
frontend/public/locales/fr/hamburguer-menu.json
frontend/public/locales/fr/header.json
frontend/public/locales/fr/login.json
frontend/public/locales/fr/owned-filter.json
frontend/public/locales/fr/pages/community.json
frontend/public/locales/fr/pages/overview.json
frontend/public/locales/fr/rarity-filter.json

As discussed in #220. This PR is the French translation of the web page and not the translation of all cards btw.

feat: added french translation thanks to @CraazyyGiirl 🇫🇷

---

frontend/public/locales/fr-FR/expansion-overview.json
frontend/public/locales/fr-FR/gradient-card.json
frontend/public/locales/fr-FR/number-filter.json
frontend/public/locales/fr-FR/pages/overview.json

Hello,
I added a missing JSON file for the French locale. Also did some fixes in the translation to have something more natural.

fix: more natural french translations (+ missing strings)

---

.all-contributorsrc
README.md
frontend/package.json
frontend/src/components/CardsTable.tsx
frontend/src/components/Header.tsx
frontend/src/components/RarityFilter.tsx
frontend/src/lib/CardsDB.ts
frontend/src/pages/collection/Collection.tsx
frontend/src/pages/overview/Overview.tsx
frontend/src/pages/overview/components/CompleteProgress.tsx
frontend/src/pages/overview/components/ExpansionOverview.tsx
frontend/src/pages/trade/Trade.tsx
frontend/src/types/index.ts
pnpm-lock.yaml

[Add type definition for rarities](https://github.com/marcelpanse/tcg-pocket-collection-tracker/commit/756dacb2877299988648e806609f02e3668c5f0e)
[put card scanner in separate chunk](https://github.com/marcelpanse/tcg-pocket-collection-tracker/commit/ecda826eb3bb6101c9874128ca7ba8e707992028)

Add type definition for rarities + card scanner chunk + dependabot updates

---

frontend/public/locales/en-US/gradient-card.json
frontend/public/locales/en-US/hamburguer-menu.json
frontend/src/components/Header.tsx
frontend/src/components/ui/alert.tsx
frontend/src/components/ui/toggle.tsx
frontend/src/pages/overview/components/GradientCard.tsx
frontend/src/pages/trade/Trade.tsx

see suggested UI tweaks here:
[https://excalidraw.com/#json=ELqsVApYY4pT2tiKGFwCN,9BgimWE_LtxOyHvrBFC9ng](https://excalidraw.com/#json=ELqsVApYY4pT2tiKGFwCN,9BgimWE_LtxOyHvrBFC9ng)

UI tweaks 1-4

---

frontend/src/components/ui/progress-custom.tsx
frontend/src/pages/overview/components/CompleteProgress.tsx
frontend/src/pages/overview/components/ExpansionOverview.tsx

feat: implement custom progress component with dynamic bar color

---

frontend/src/components/Header.tsx

The logo has been added to the header to improve brand recognition and visual appeal. The layout was adjusted to ensure proper alignment and spacing between the logo and the title.
Desktop
Before
After
Mobile
Before
After

style(Header): add logo and adjust layout for better visual consistency

---

frontend/public/locales/it-IT/common/packs.json
frontend/public/locales/it-IT/common/sets.json
frontend/public/locales/it-IT/edit-profile.json
frontend/public/locales/it-IT/trade-matches.json

Add Italian translations for Celestial Guardians set.
Update some other translations.

chore(ita): add Celestial Guardians translations

---

frontend/public/locales/en-US/login.json
frontend/src/components/Login.tsx

shortened & updated the login for readability
before:
---
after:

tweaks 11&12

---

frontend/public/locales/it-IT/number-filter.json

Resolved a minor typo for "numberCards" translation

Fix minor typo in it-IT\number-filter.json

---

frontend/public/locales/it-IT/common/packs.json
frontend/public/locales/it-IT/common/sets.json

Add Italian translations for Extradimensional Crisis set.

chore(ita): add Extradimensional Crisis translations

---

frontend/assets/trainers_translations.json

volkner typo

---

frontend/public/locales/es-ES/common/sets.json
frontend/public/locales/fr-FR/common/sets.json
frontend/public/locales/it-IT/common/sets.json

Got the name from:
- ES: https://www.wikidex.net/wiki/Arboleda_de_Eevee_(TCG_Pocket)
- FR: https://www.pokepedia.fr/La_Clairi%C3%A8re_d%27%C3%89voli
- IT: https://wiki.pokemoncentral.it/Il_Bosco_di_Eevee_(GCC_Pocket)

feat(eevee): updated translations for ES, FR and IT

---

frontend/assets/themed-collections/A1-missions.json
frontend/assets/themed-collections/A3b-missions.json
frontend/src/pages/collection/CardDetail.tsx
frontend/src/pages/collection/MissionDetail.tsx
scripts/scrape-missions.js

Addresses https://github.com/marcelpanse/tcg-pocket-collection-tracker/issues/496 and adds A3b missions.

A1 missions fix and a3b

---

frontend/assets/tools_translations.json

- added localization for leftovers in all languages currently covered

chore: added translation entries for "leftovers"

---

frontend/assets/pokemon_translations.json
frontend/assets/tools_translations.json
frontend/assets/trainers_translations.json
scripts/sync-translations.js

Last one for today, I added a script that add all missing pokémon/tools/trainers to the translations json files and I've added the french translation for all missing string.

feat: add script to synchronize assets translations

---

frontend/src/App.tsx
frontend/src/components/CardsTable.tsx
frontend/src/lib/fetchCollection.ts
frontend/src/main.tsx
frontend/src/pages/collection/Collection.tsx
frontend/src/pages/overview/Overview.tsx

Fixes #594
Fixes #596 
The fix was simply to remove window.location.reload(). From my testing, this solves the issue, but I don’t know why it was there in the first place. I’d appreciate it if you could confirm that removing it doesn’t break anything.

Remove collection reload

---

frontend/src/components/filters/NumberFilter.tsx
frontend/src/pages/trade/TradeOffers.tsx
frontend/src/pages/trade/TradeWith.tsx
frontend/src/pages/trade/components/CardList.tsx
frontend/src/pages/trade/components/TradeOffer.tsx

Improve `TradeWith` responsiveness

---

frontend/src/App.tsx

Fixes this: https://community.tcgpocketcollectiontracker.com/t/unable-to-view-public-trade-page-links/6821
From now onward I'll include the list of what I tested, maybe that will encourage me to do a deeper testing 🫤
Tested:

Fix old trade path handler

---

frontend/src/pages/trade/TradeCards.tsx

Hide untradable cards from `TradeCards`

---

frontend/assets/cards/A1.json
frontend/assets/cards/A1a.json
frontend/assets/cards/A2.json
frontend/assets/cards/A2a.json
frontend/assets/cards/A2b.json
frontend/assets/cards/A3.json
frontend/assets/cards/A3a.json
frontend/assets/cards/A3b.json
frontend/assets/cards/A4.json
frontend/assets/cards/A4a.json
frontend/assets/cards/A4b.json
frontend/assets/cards/P-A.json
frontend/src/lib/CardsDB.ts
frontend/src/pages/collection/CardDetail.tsx
frontend/src/pages/collection/Missions.tsx
frontend/src/types/index.ts
package.json
scripts/scraper.js
scripts/scraper.ts
tsconfig.json

- Use typescript in the card scraper
- Move the `CardDB.ts:update()` logic to card scraper
- Replace keeping `crafting_cost` on each card with a dictionary lookup by rarity

Card scraper improvements
