marcelpanse/tcg-pocket-collection-tracker

frontend/src/pages/collection/components/Cards.tsx
This PR addresses the issue of scroll position resetting to 0 upon re-rendering in React Table. The fix involves saving the scroll position in [localStorage] and restoring it when the component mounts. This ensures that the scroll position is maintained even after the component re-renders.
This is problem from React Table https://github.com/TanStack/table/issues/963
- #74
=> Fix scroll position restoration issue in React Table

frontend/src/pages/trade/LookingFor.tsx
#129 
Fixed to look for owned cards with 0 amount_owned as well as the card not found in the ownedCards collection
=> Fix Looking For Bug

frontend/src/pages/trade/Trade.tsx
Made the option text force to black (because the backgrounds are white or light gray.
#232
=> Fixed Dropdown Colors for Trade Page

frontend/src/components/BatchUpdateDialog.tsx
Resolves #229 
We could also consider reducing dialog width or increase cards size to keep the original visual gap between cards.
=> (#229) fix: batch update - display 5 cols

frontend/src/components/RarityFilter.tsx, frontend/src/lib/CardsDB.ts, frontend/src/pages/collection/Collection.tsx, frontend/src/pages/overview/Overview.tsx, frontend/src/pages/overview/components/CompleteProgress.tsx, frontend/src/pages/overview/components/ExpansionOverview.tsx, frontend/src/pages/trade/Trade.tsx, frontend/src/types/index.ts
Thanks for making such a cool project!
I was having a browse and thought there might be a good opportunity to use TypeScript to improve the type safety when handling rarities within the app.
A couple of thoughts:
1. I tried to avoid adding entries for every rarity to each object by having separate types like `PickableRarity`, etc, but actually in the end I thought it was probably good practice to have a single type and handle each possible value explicitly.
2. I was wondering why there are two different rarities for promo cards ("" and "Unknown"), do you think this is something that could be simplified? I'm not sure if this is something the scraper would handle, I didn't look at that part too closely.
I'm very open to any suggestions you might have, and if you don't like it at all then …
=> Add type definition for rarities

frontend/package.json, frontend/public/locales/en-US/deckbuilding-filter.json, frontend/public/locales/es-ES/deckbuilding-filter.json, frontend/public/locales/fr-FR/deckbuilding-filter.json, frontend/public/locales/pt-BR/deckbuilding-filter.json, frontend/src/components/Card.tsx, frontend/src/components/DeckbuildingFilter.tsx, frontend/src/components/InstallPrompt.tsx, frontend/src/components/RarityFilter.tsx, frontend/src/lib/CardsDB.ts, frontend/src/pages/overview/Overview.tsx, frontend/src/pages/overview/components/CompleteProgress.tsx, frontend/src/pages/overview/components/ExpansionOverview.tsx, pnpm-lock.yaml
Closes #275
Adds a checkbox that allows the user to treat full-art cards like basic cards when counting how many are already owned and the chance of getting a "new" card.
This new filter is called "Deck-building Mode". A tooltip explaining the mode has been added in desktop mode. In mobile it seemed too large and in-the way.
Card counts change when this mode is turned on.
When this filter is turned on, the star and crown rarities are removed from the rarity filter, as they no longer make sense.
Images highlight changes that are made between modes:
=> 275 checkbox to combine fullart and regular cards

frontend/assets/pokemon_translations.json, frontend/src/components/Card.tsx, frontend/src/components/CardMiniature.tsx, frontend/src/components/FancyCard.tsx, frontend/src/components/FiltersPanel.tsx, frontend/src/components/PokemonCardDetectorComponent.tsx, frontend/src/lib/utils.ts, frontend/src/pages/collection/CardDetail.tsx
This PR adds a new JSON file at frontend/assets/pokemon_translations.json containing Pokémon names in various languages.
The data is based on the pokemon_species_names.csv file from the [PokeAPI GitHub repository](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species_names.csv).
For now, translations for trainers and items are not included.
https://github.com/user-attachments/assets/ee1c6c73-aed9-4789-90f3-39988bb77479
=> feat: add cards names in differents languages

frontend/public/locales/it-IT/common/packs.json, frontend/public/locales/it-IT/common/sets.json, frontend/public/locales/it-IT/common/types.json, frontend/public/locales/it-IT/complete-progress.json, frontend/public/locales/it-IT/deckbuilding-filter.json, frontend/public/locales/it-IT/edit-profile.json, frontend/public/locales/it-IT/expansion-overview.json, frontend/public/locales/it-IT/gradient-card.json, frontend/public/locales/it-IT/hamburguer-menu.json, frontend/public/locales/it-IT/header.json, frontend/public/locales/it-IT/login.json, frontend/public/locales/it-IT/number-filter.json, frontend/public/locales/it-IT/owned-filter.json, frontend/public/locales/it-IT/pages/card-detail.json, frontend/public/locales/it-IT/pages/collection.json, frontend/public/locales/it-IT/pages/overview.json, frontend/public/locales/it-IT/rarity-filter.json
Add Italian translation for all translatable text.
Tested locally.
A few issues:
- some text is not translated (e.g. "Scan", "Sign up to view your tradeable cards", "X selected, X uniques owned, X total owned" in the Collection page, etc.) -> they feel a bit off, it would be great to transalate them as well (if I can find some time I can try to understand how to do it)
- there is a small bug that prevents the text to be displayed correctly (it displays the key name and not the translated value):
As you can see, it says "mewtwo, charizard, pikachu" instead of the correct names (in English should be "Mewtwo pack, Charizard pack, Pikachu pack"). At a quick look, the issue is that the `GradientCard` component receives - for instance - "mewtwo" as key but it should instead receive …
=> feat: add Italian translation

frontend/public/locales/en-US/common/packs.json, frontend/public/locales/en-US/gradient-card.json, frontend/public/locales/en-US/pages/overview.json, frontend/public/locales/es-ES/common/packs.json, frontend/public/locales/es-ES/pages/overview.json, frontend/public/locales/pt-BR/gradient-card.json, frontend/public/locales/pt-BR/pages/overview.json, frontend/src/components/FiltersPanel.tsx, frontend/src/components/filters/ExpansionsFilter.tsx, frontend/src/components/filters/PackFilter.tsx, frontend/src/pages/collection/Collection.tsx, frontend/src/pages/overview/Overview.tsx, frontend/src/pages/overview/components/ExpansionOverview.tsx
Change 1: Add Pack filter to address https://github.com/marcelpanse/tcg-pocket-collection-tracker/issues/353.
The list of packs changes with the choice of expansion, and resets to "All packs" when a new expansion is chosen. Utilizes translations set in common/packs. When a pack other than "All packs" is chosen, it shows cards in that pack + everypack cards for that expansion. For expansions with only one pack, it just has the "All packs" option. First time working in frontend, so I copied the existing expansions code mostly. I would be willing to look into making it a dropdown if that's preferred.
Change 2: Uses pack translation names on the overview tab. 
Mild edits to some translations to make more grammatical sense. Still no "and" between pack names but oh well 🤷. I used Google …
=> Add pack filter and translatable pack names

supabase/functions/stats-tracker/index.ts
Potential fix for [https://github.com/marcelpanse/tcg-pocket-collection-tracker/security/code-scanning/6](https://github.com/marcelpanse/tcg-pocket-collection-tracker/security/code-scanning/6)
To fix the issue, we should avoid exposing the raw `err` object to the user. Instead, we can log the detailed error information on the server for debugging purposes and return a generic error message to the user. This ensures that sensitive information, such as stack traces, is not leaked while still allowing developers to diagnose issues.
The fix involves:
1. Logging the error details (e.g., stack trace) to the server console using `console.error`.
2. Returning a generic error message (e.g., "An internal server error occurred") to the user in the HTTP response.
---
_Suggested fixes powered by …
=> Potential fix for code scanning alert no. 6: Information exposure through a stack trace

frontend/assets/cards/A3.json, frontend/src/pages/overview/components/GradientCard.tsx
Addresses https://github.com/marcelpanse/tcg-pocket-collection-tracker/issues/372
Also fixes alignment for shining revelry words in overview:
Before:
After:
=> Fix names with ex & shining revelry alignment

frontend/src/components/Header.tsx
I updated the header styles to improve the layout on larger monitors.
=> fix: adjust header styling for better layout and alignment

frontend/src/components/CardsTable.tsx, frontend/src/components/FancyCard.tsx, frontend/src/components/filters/ExpansionsFilter.tsx
Improve the visual representation of expansions by displaying set images alongside their names in the expansion tabs and table headers. This change enhances user experience by making it easier to identify sets at a glance.
=> feat(filters): enhance UI by adding set images to expansion tabs and table headers

frontend/src/components/RadialChart.tsx, frontend/src/pages/overview/Overview.tsx
The RadialChart component is introduced to visually represent the percentage of unique cards owned by the user. This enhances the user experience by providing a more intuitive and engaging way to view progress. The component is integrated into the Overview page, replacing the previous text-based display of card ownership.
=> feat(overview): add RadialChart component to display card ownership progress

frontend/public/locales/en-US/complete-progress.json, frontend/src/components/RadialChart.tsx, frontend/src/components/ui/progress-custom.tsx, frontend/src/pages/overview/Overview.tsx
Commit #1 
before: 
after:
---
Commit #2
before:
after:
---
Commit #3
before (see commit #1)
after:
=> UI tweaks (5, 6)

frontend/assets/themed-collections/A1-missions.json, frontend/assets/themed-collections/A1a-missions.json, frontend/assets/themed-collections/A2a-missions.json
This mission to get the immersive Mew by collecting the other 150 Kanto pokemon wasn't present on the site I scraped from. Luckily @PlayInKetchup wrote it up originally, so I recovered it and just tweaked to fit the format.
There are also some non-card missions which need removal.
=> Add immersive mew mission

frontend/assets/cards/P-A.json, scripts/scraper.js
Fixes https://community.tcgpocketcollectiontracker.com/t/new-promo-cards-have-wrong-rarity/4677
Looks like the site that cards are scraped from is now adding the rarities, so existing logic to apply P rarity to cards without a rarity didn't work. Modified scraper to just set all P-A cards to P rarity.
=> change to P rarity for a3a promo cards

frontend/src/components/PokemonCardDetectorComponent.tsx, frontend/src/services/CardHashStorageService.ts, frontend/src/services/ImageHashingService.ts
I did some optimizations in the hashing. The time gains were so big, that allowed to increase the hash length by 4 while still being faster. The increased hash length makes the recognition *much* more accurate, and because the memory optimization (they are tightly packed in bit arrays) they should still take about 2 times less space.
The problem for me now is how to trigger recomputation of hashes for the users. I think it would be best to use a different store name and delete the old one (to avoid any complicated checking of hash version), but I couldn't figure out how to do this (I am not very familiar with js).
=> Improve scanning hashes

frontend/public/locales/en-US/trade-matches.json, frontend/src/pages/collection/TradeMatches.tsx, frontend/src/types/index.ts
I accidentally closed #451 due to git miss handling, reopening.
This adds the second case I raised in https://github.com/marcelpanse/tcg-pocket-collection-tracker/issues/309#issuecomment-2868939009.
Currently, I'm getting an error when trying to submit the form (as expected). But I don't know (I'm not familiar with any frontend/web architecture) if there needs to be some additional changes in this PR, or the backend just has to be redeployed (I was basing myself on [this commit](https://github.com/marcelpanse/tcg-pocket-collection-tracker/commit/0f4d47f87ee9b889c09579b4537c5188f064998d) and didn't find anything else to change).
=> feat: #309 trade max cards input

frontend/src/components/FancyCard.tsx
Fixes #426 by adding transform override exclusive to firefox. 
The comparison of the old and updated behaviour can be seen in that Issue
=> fix: firefox 3D hover effect

frontend/src/App.tsx, frontend/src/components/Footer.tsx, frontend/src/components/LicenseModal.tsx
- added a footer on overview page to disclose the project is not affiliated to the parent companies of the game and declare their trademarks
- added modal component invoked with footer to fully disclose the project's GNU License, © of TCG Pocket Collection Tracker and a more robust disclaimer about the owners of the respective trademarks and assets
=> add footer on homepage + modal with licenses disclaimer

frontend/src/components/CardsTable.tsx
- fix scrolling on phone to avoid side-wiggles
- extra offset to remove scrollbars on desktop's collection page since it served no purpose, and we scroll the cards table
- this extra offset is not considered if mobile device is detected to avoid cutting off content visually on phones
I also tested this on 4K resolution, Android, iOS. 
It should work just fine but of course let me know if any change is needed or feel free to edit later.
Here's a video of a side by side comparison of the behaviour on live website vs my edits on desktop and a screen recording of the wiggling behaviour on phone also addressed in this commit.
https://github.com/user-attachments/assets/5525700d-97f2-4148-a3e1-847501fa8ca2
https://github.com/user-attachments/assets/412c6377-4594-4cc6-bd14-a68bbe5dba5c
=> fix phone scrolling + remove need for desktop scrollbar on collection page

frontend/public/locales/en-US/common/sets.json, frontend/src/components/FiltersPanel.tsx, frontend/src/components/filters/ExpansionsFilter.tsx, frontend/src/components/filters/PackFilter.tsx, frontend/src/pages/overview/Overview.tsx
As there are more and more expansions, the tabs filter becomes less and less viable, which eventually would need to be addressed. This PR does it by changing it from tabs to dropdown.
=> Expansions filter as dropdown

frontend/assets/cards/A4.json, frontend/assets/cards/P-A.json, frontend/public/locales/en-US/pages/card-detail.json, frontend/src/lib/CardsDB.ts, frontend/src/pages/collection/CardDetail.tsx, frontend/src/types/index.ts, scripts/scraper.js
Fixes #533
With the introduction of baby pokemon in A4, the way the odds for each card are calculated needed to be updated as there is now a new 6-card pack that has distinct from the regular and rare packs from previous expansions. Baby can strictly be found as the 6th card in a 6-card pack.
This PR updates the scraper.js script to add a "baby" field to each of the cards. Currently the Limitless TCG site doesn't have a baby field, but at the moment all baby pokemon are basic, have 30 health, and have no weaknesses.
The only cards with no weaknesses are dragon-type and babies for now, and there are no dragon-type baby pokemon, so this should be sufficient to distinguish the cards, but the basic and health criteria are added as extra security.
The odds calculator function has been updated …
=> Fix card odds calculations to handle A4 baby pokemon

frontend/src/components/FiltersPanel.tsx
Fix card sorting to handle IDs in true numerical order.
Fixes #544
=> Add true numerical ordering to sort by expansion

frontend/src/pages/decks/DeckItem.tsx
Fixes #557 
Reworked the `isSelected`. From what I tested, seems like we were stopping on first match and stopped counting successive alternate card matches.
From my card collection, I have 2 Darkrai Ex card, the basic one and the 2 :star: one. Before I had the second Darkrai missing, now both the card are marked owned. The missing count is also correct.
Before: <img width="2000" height="817" alt="image" src="https://github.com/user-attachments/assets/410e4e33-7fbb-4588-8f9d-623b6f243311" />
After: <img width="2000" height="827" alt="image" src="https://github.com/user-attachments/assets/e2fb69b5-4384-45aa-94c3-b0ff8c618b8c" />
=> fix(decks): properly count alternate versions for deck validation

frontend/src/lib/CardsDB.ts
Fixes #591 
I've ran a script to list all the probabilities for each card, and only the Crown Rare of the latest expansion is affected by this change.
```diff
- A4a-105: 0.000000%
+ A4a-105: 0.206769%
```
=> fix: pull rate probability for Crown Rare Baby (A4a-105)

frontend/public/locales/en-US/common.json, frontend/public/locales/en-US/pages/collection.json, frontend/src/App.tsx, frontend/src/components/CardsTable.tsx, frontend/src/components/FiltersPanel.tsx, frontend/src/components/filters/ExpansionsFilter.tsx, frontend/src/components/filters/PackFilter.tsx, frontend/src/pages/collection/Collection.tsx, frontend/src/pages/collection/CollectionCards.tsx, frontend/src/pages/collection/Missions.tsx, frontend/src/pages/trade/TradeWith.tsx
Currently missions are considered as packs and deeply coupled with you collection in `Collection.tsx` and `FiltersPanel.tsx` (which does `filteredCards = []` when you choose the "mission pack", which is, lest say, unconventional). This has some non-obvious consequences:
- When viewing missions, you still have all the filters panel available, but it mostly doesn't work. For example, you can change the mission rarity/energy type/maximum number of cards owned, or search for a text, but these doesn't influence the missions shown in any way. This might be confusing for the user who expects to find the 5 charizard mission by typing the card name in the search box.
- You can switch to missions in friends collection. But it actually shows your missions, not friends. It shouldn't behave this way. …
=> Decouple collection and missions

frontend/src/components/CardLine.tsx
Currently when you click the "card details" button in the `CardLine` component, it opens the sheet and also triggers the `onClick` (for example adding the card to trade offer). This prevents that.
=> CardLine stop propagation

frontend/public/locales/de-DE/trade-matches.json, frontend/public/locales/en-US/trade-matches.json, frontend/public/locales/fr-FR/trade-matches.json, frontend/src/pages/trade/TradeOffers.tsx, frontend/src/pages/trade/components/TradeList.tsx, frontend/src/pages/trade/components/TradePartner.tsx
Closes #658. I removed the "no active trade" message to save some space. The page now looks much shorter:
Before:
After:
=> Fix duplicate trade partners
